version: "3.8"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  dodo:
    build: ./dodo-github-visualization
    environment:
      SECRET_COOKIE_PASSWORD_FILE: /run/secrets/cookie_password
    container_name: "dodo-visualization"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dodo.rule=PathPrefix(`/`)"
      - "traefik.http.routers.dodo.entrypoints=web"
    secrets:
      - cookie_password

  dbservice:
    build: ./dodo-database-service
    environment:
      SECRET_DB_PASSWORD_FILE: /run/secrets/db_password
    container_name: "dodo-db-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=PathPrefix(`/db-service`)"
      - "traefik.http.routers.db.entrypoints=web"
    secrets:
      - db_password    

  mongodb:
    image: mongo
    container_name: mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=PathPrefix(`/database`)"
    secrets:
      - mongo_root_pw
      - mongo_root_username

    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_root_pw
      - MONGO_INITDB_DATABASE=githubMirror
      - DB_USER_FILE=/run/secrets/mongo_user_username # the first two secrets are handled by the offical mongo docker image
      - DB_USER_PASSWORD_FILE=/run/secrets/mongo_user_pw # the user related are handled in the custom mongo-init.sh
    volumes:
      - mongodb-data:/data/db
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - mongodb_network

    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=PathPrefix(`/db-admin`)"
      - "traefik.http.routers.db.entrypoints=web"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
      - mongodb-data:/data/db
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    restart: unless-stopped
volumes:
  mongodb-data:
networks:
  mongodb_network:
secrets:
  cookie_password:
    file: secrets/cookie_password.txt
  mongo_root_pw:
    file: secrets/mongo_root_pw.txt
  mongo_root_username:
    file: secrets/mongo_root_username.txt

  mongo_user_pw:
    file: secrets/mongo_user_pw.txt
  mongo_user_username:
    file: secrets/mongo_user_username.txt
