version: "3.3"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  dodo:
    build: ./dodo-github-visualization
    environment:
      SECRET_COOKIE_PASSWORD_FILE: /run/secrets/cookie_password
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dodo.rule=Host(`dodo.localhost`)"
      - "traefik.http.routers.dodo.entrypoints=web"
    secrets:
      - cookie_password

secrets:
  cookie_password:
    file: cookie_password.txt
